### ISSUE TITLE
can NodeSSPI be pkg?

### ISSUE THREAD

**Issue by JasonCubic** [abbr/NodeSSPI#57]
when trying to package using this:  https://github.com/zeit/pkg I get the below error when I try to run the package.  Has anyone seen this?  What is a bindings file?  How can I fix this error?  Thanks,

```
pkg/prelude/bootstrap.js:1176
      throw error;
      ^

Error: Could not locate the bindings file. Tried:
 → C:\snapshot\widget-api\node_modules\node-sspi\build\nodeSSPI.node
 → C:\snapshot\widget-api\node_modules\node-sspi\build\Debug\nodeSSPI.node
 → C:\snapshot\widget-api\node_modules\node-sspi\build\Release\nodeSSPI.node
 → C:\snapshot\widget-api\node_modules\node-sspi\out\Debug\nodeSSPI.node
 → C:\snapshot\widget-api\node_modules\node-sspi\Debug\nodeSSPI.node
 → C:\snapshot\widget-api\node_modules\node-sspi\out\Release\nodeSSPI.node
 → C:\snapshot\widget-api\node_modules\node-sspi\Release\nodeSSPI.node
 → C:\snapshot\widget-api\node_modules\node-sspi\build\default\nodeSSPI.node
 → C:\snapshot\widget-api\node_modules\node-sspi\compiled\8.11.3\win32\x64\nodeSSPI.node
    at bindings (C:\snapshot\widget-api\node_modules\bindings\bindings.js:93:9)
    at Object.<anonymous> (C:\snapshot\widget-api\node_modules\node-sspi\index.js:20:31)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (module.js:661:10)
    at Module.load (module.js:563:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:594:17)
    at Module.require (pkg/prelude/bootstrap.js:1157:31)
    at require (internal/module.js:11:18)
```

**Comment by abbr** [comment]
I believe this is an issue of packager rather than *NodeSSPI*, for example https://github.com/zeit/pkg/issues/117
