### ISSUE TITLE
Support Node LTS v12.13.0

### ISSUE THREAD

**Issue by sagitsofan** [abbr/NodeSSPI#76]
When i upgraded my node to LTS v12.13.0, node-sspi package was break.
Can we except for a fix in the near future @abbr?
Following is the error:

```
Error: Could not locate the bindings file. Tried:
 → c:\proj\node\node_modules\node-sspi\build\nodeSSPI.node
 → c:\proj\node\node_modules\node-sspi\build\Debug\nodeSSPI.node
 → c:\proj\node\node_modules\node-sspi\build\Release\nodeSSPI.node
 → c:\proj\node\node_modules\node-sspi\out\Debug\nodeSSPI.node
 → c:\proj\node\node_modules\node-sspi\Debug\nodeSSPI.node
 → c:\proj\node\node_modules\node-sspi\out\Release\nodeSSPI.node
 → c:\proj\node\node_modules\node-sspi\Release\nodeSSPI.node
 → c:\proj\node\node_modules\node-sspi\build\default\nodeSSPI.node
 → c:\proj\node\node_modules\node-sspi\compiled\12.13.0\win32\x64\nodeSSPI.node
 → c:\proj\node\node_modules\node-sspi\addon-build\release\install-root\nodeSSPI.node
 → c:\proj\node\node_modules\node-sspi\addon-build\debug\install-root\nodeSSPI.node
 → c:\proj\node\node_modules\node-sspi\addon-build\default\install-root\nodeSSPI.node
 → c:\proj\node\node_modules\node-sspi\lib\binding\node-v72-win32-x64\nodeSSPI.node
    at bindings (c:\proj\node\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (c:\proj\node\node_modules\node-sspi\index.js:20:31)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (c:\proj\node\api-gateway\src\server\server.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)

```

Missing node-12 bindings in the bin folder:
![image](https://user-images.githubusercontent.com/1827994/67692490-e26b1000-f9a8-11e9-89b6-212fd13e8bb8.png)

**Comment by abbr** [comment]
fixed in node-sspi@0.2.6
