### ISSUE TITLE
Install fails with SSL-intercepting proxy

### ISSUE THREAD

**Issue by voltagex** [abbr/NodeSSPI#9]
I can't fix the SSL interception issue and I don't know why I'm not getting a pre-built binary.

npm install node-sspi is failing with

```
c:\developer\test\node_modules\node-sspi>if not defined npm_config_node_gyp (nod
e "C:\Program Files\iojs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\n
ode-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to verify the first certificate
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:926:38)
gyp ERR! stack     at emitNone (events.js:67:13)
gyp ERR! stack     at TLSSocket.emit (events.js:163:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:511:8)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\iojs\\node.exe" "C:\\Program Files\\iojs\\n
ode_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\developer\test\node_modules\node-sspi
gyp ERR! node -v v2.0.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\iojs\\node.exe" "C:\\Program Files\\iojs\\node
_modules\\npm\\bin\\npm-cli.js" "install" "node-sspi" "--debug"
npm ERR! node v2.0.1
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE

npm ERR! node-sspi@0.1.8 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sspi@0.1.8 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the node-sspi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sspi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\developer\test\npm-debug.log
```

**Comment by voltagex** [comment]
Apologies, looks like this is a node-gyp issue

**Comment by voltagex** [comment]
For anyone else looking at this, run 

```bash
set NODE_TLS_REJECT_UNAUTHORIZED=0 #(or equivalent for your platform)
npm install node sspi
```
